version: "3.4"

services:
  consul:
    image: "consul:latest"
    ports:
      - "8300:8300"
      - "8500:8500"
      - "8600:8600"
    environment:
      - "CONSUL_BIND_INTERFACE=eth0"
  vault:
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      - "VAULT_DEV_ROOT_TOKEN_ID=vault"
    cap_add:
      - IPC_LOCK
    volumes:
      - ".vault:/var/log/vault"
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"
  rabbit:
    image: "rabbitmq:management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
